S_WAITING = "waiting"
S_READY = "ready"
S_TRANSFERRING = "transferring"
S_FINISHED = "finished"
S_CANCELLED = "cancelled"

ACTIVE_STATUSES = (S_WAITING, S_TRANSFERRING, S_READY)
FINISHED_STATUSES = (S_FINISHED, S_CANCELLED)
AWAITING_PICKUP = (S_READY, S_TRANSFERRING)
CANCELLABLE_STATUSES = (S_WAITING, S_READY)


ALLOWED_FROM = {
    S_READY: {S_WAITING},
    S_TRANSFERRING: {S_WAITING},
    S_FINISHED: {S_READY, S_TRANSFERRING},
    S_CANCELLED: {S_WAITING, S_READY},
}
